name: india_air_quality_json

on:
#   workflow_dispatch:
  # Uncomment the following lines to enable scheduled runs
  schedule:
    - cron: '45 * * * *'  # Runs every 45th minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8.1'  # Specify your desired Python version

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Install numpy first
        run: |
          pip install numpy==1.23.5  # Adjust version as needed
      
      - name: Install dependencies
        run: |
          pip install snowflake-snowpark-python==1.5.1 pandas==1.5.3
      
      - name: List files
        run: |
          ls -la
          pwd
      
      - name: Run Python script
        run: |
          python ingest-api-data.py
